### ISSUE TITLE
Will the test file be available? 

### ISSUE THREAD

**Issue by chenrxi** [fatemeh-slh/ArTIST#2]

**Comment by EmpireofKings** [comment]
It is available

**Comment by chenrxi** [comment]
How can i use? I just see two demos. I want to test the metric of mot17

**Comment by chenrxi** [comment]
No! Is the tracking algorithm available? I want to evaluate the tracking performance of ArTIST? I can not find it except two demos.  

> It is available

@sadegh-aa @fatemeh-slh

**Comment by fatemeh-slh** [comment]
Note that this repository contains the ArTIST motion model. For tracking, you need to use it in your tracking algorithm of choice. The two important functions of ArTIST motion model have been provided which are _scoring_ and _inpainting_. You can use these functions in any tracker. For example, you can simply replace the Kalman Filter algorithm in [SORT](https://github.com/abewley/sort) with ArTIST motion model.

**Comment by chenrxi** [comment]
code is difficult to understand

**Comment by vineetrshenoy** [comment]
Do you have an example of integrating the ArTIST motion model with SORT?

**Comment by chenrxi** [comment]
![image](https://user-images.githubusercontent.com/60959000/126484688-beeaea28-c927-4c97-83b9-8796bd6a7d2c.png)
the nll function is very inaccurate, for example i change the masked_index to another rate such as 0.1, 0.2 to change the seq_len in the demo_scoring.py, it cannot predict the right score for gt box(nearest to 0).
could you provide your inference code(including tracking algorithm) and it will be a great help to me.
@fatemeh-slh
