### ISSUE TITLE
Re-creating paper results

### ISSUE THREAD

**Issue by vineetrshenoy** [fatemeh-slh/ArTIST#4]
Did you use implement the ArTIST paradigm in the SORT algorithm to achieve the results in your paper? If so, do you have an example of integrating the ArTIST motion model with SORT? I am trying to re-create the results of the paper.

How do I re-create the results you obtained in your paper?

**Comment by chenrxi** [comment]
Have you get some results. I only get MOTA of 53, due to many idswes

**Comment by fatemeh-slh** [comment]
Please see:
https://github.com/fatemeh-slh/ArTIST/issues/3#issuecomment-887691683
